<a href="https://colab.research.google.com/github/kaniarasann/AI-Expert-Roadmap/blob/main/02_numply_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

slicing

In [ ]:
import numpy as np

In [ ]:
array_a = np.array([1,2,3,4,5,6,7,8,9,10])
array_b = np.array([[1,2,3,4,5],[6,7,8,9,10]])

Basic Slicing

In [ ]:
array_b[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
array_b[0:0]

array([], shape=(0, 5), dtype=int64)

In [ ]:
array_b[0:1]

array([[1, 2, 3, 4, 5]])

In [ ]:
array_b[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#exludes the first row
array_b[:1]

array([[1, 2, 3, 4, 5]])

In [ ]:
#exludes the first row
array_b[1:]

array([[ 6,  7,  8,  9, 10]])

In [ ]:
array_b[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
array_b[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#nagative index
array_b[-1:]

array([[ 6,  7,  8,  9, 10]])

In [ ]:
array_b[:-1]

array([[1, 2, 3, 4, 5]])

In [ ]:
#column slicing
array_b[:,1]

array([2, 7])

In [ ]:
array_b[1:,1:]

array([[ 7,  8,  9, 10]])

In [ ]:
array_b[0:-1,:-1]

array([[1, 2, 3, 4]])

Stepwise Slicing - we take values at certian places apart

1.   Step Argument cant be negative
2.   [start:stop:step]



In [ ]:
matrix_3row = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [ ]:
matrix_3row[::,::]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
matrix_3row[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

In [ ]:
#If set step argumanet as negative it starts from the row bottom
matrix_3row[::-2]

array([[11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5]])

In [ ]:
#If set step argumanet as negative it starts from the row bottom
matrix_3row[::-2,::-2]

array([[15, 13, 11],
       [ 5,  3,  1]])

In [ ]:
matrix_3row[2::-1]

array([[11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

Conditional Slicing

it flattens out the whole array in single dimensional

In [ ]:
matrix_c = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [ ]:
matrix_c[matrix_c<5]

array([1, 2, 3, 4])

In [ ]:
#check in column
matrix_c[:,0]>5

array([False,  True,  True])

In [ ]:
#using and condition
matrix_c[(matrix_c%2 == 0) & (matrix_c>5)]

array([ 6,  8, 10, 12, 14])